name:  Synapse-workflow

on:
  push:
    branches: [ main, test ]

jobs:

  deploy-testing:
    name: Deploy to testing
    environment:
      name: Testing
    if: github.event.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    steps:
      - name: Create Dispatch Event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: syedimranFB/multi-stage-test
          event-type: my-custom-event